### ISSUE TITLE
Docker container not using GPU

### ISSUE THREAD

**Issue by JosephKuchar** [opengeos/segment-geospatial#201]
Hi,

I'm running samgeo through the docker container, following the instructions here: 

https://samgeo.gishub.org/installation/

I've installed the NVIDIA container toolkit, and the benchmark seems to run fine:

![image](https://github.com/opengeos/segment-geospatial/assets/3575111/d79c8d0d-2b82-4bc0-a3e5-16245249b8b4)

However, when we try to run the satellite workbook example, we find it uses nearly 100% of our CPU, and is not using the GPU. Is there a step we should be taking to enable it to use the GPU instead?

Thanks,

Joseph

**Comment by giswqs** [comment]
Run the following code to see if GPU is avialable. 

```python
import torch
torch.cuda.is_available()
torch.cuda.get_device_name(0)
```

**Comment by JosephKuchar** [comment]
The GPU is not available - is_available returns False, and the get_device_name command returns the following error:

> AssertionError: Torch not compiled with CUDA enabled

Can we recompile Torch within the docker container?

Thanks for your help!

**Comment by JosephKuchar** [comment]
I've built it without issue, including all steps including CUDA and PyTorch, but I don't know if any issues would show up on trying to run it.

**Comment by JosephKuchar** [comment]
I also tried running the container, and received a "No id provided" error - I don't know if the system I'm installing on is suitable for it, because reading the documentation it looks like it expects something like AWS.

**Comment by giswqs** [comment]
I am not an active docker user. Not much I can help here. I think this is a docker gpu configuration problem rather than a samgeo problem. Run the following code. If it show cuda is not available, then it is your docker gpu configration problem. If it show cuda is available, but samgeo is not utilizing gpu, then it is a samgeo problem. 

```python
import torch
torch.cuda.is_available()
torch.cuda.get_device_name(0)
```

**Comment by JosephKuchar** [comment]
I am not a docker expert, but I imagine it's the docker image - assuming the dockerfile is https://github.com/opengeos/segment-geospatial/blob/main/Dockerfile, then I don't see anything in it that would enable CUDA. I'll see if I can modify the dockerfile, I'll let you know what I ultimately come up with.

**Comment by giswqs** [comment]
You are right, the smageo Dockerfile doesn't include cuda. You are welcome to contribute a cuda version Dockerfile to samgeo

**Comment by JosephKuchar** [comment]
So, in case anyone else needs to have a docker implementation of samgeo, here is what ended up working for us:

We made use of the [GPU-Jupyter ](https://github.com/iot-salzburg/gpu-jupyter) project, which are CUDA enabled jupyter environments in docker containers. Initially we tried running one of the pre-built images and then downloading samgeo within the container, but that never worked for us. Instead, what did work was using the make_dockerfile shell script in the gpu-jupyter project. We modified the Dockerfile.useful_packages file to add samgeo and remove some things to avoid possible version conflicts:
```
RUN pip install --no-cache-dir \
    # install extension manager
    # jupyter_contrib_nbextensions==0.7.0 \
    # jupyter_nbextensions_configurator==0.6.1 \
    # install git extension
    jupyterlab-git==0.41.0 \
    # install plotly extension
    plotly==5.13.1 \
    # install drawio and graphical extensions
    jupyterlab-drawio==0.9.0 \
    rise==5.7.1 \
    segment-geospatial \
    # ipyleaflet==0.17.2 \
    # ipywidgets==8.0.4 \
```

Finally, in the generated dockerfile, we commented out this section, which uses a deprecated version of installing jupyter extensions and didn't seem necessary for our purposes to keep:

```
# Install facets which does not have a pip or conda package at the moment
#WORKDIR /tmp
#RUN git clone https://github.com/PAIR-code/facets.git && \
#    jupyter nbextension install facets/facets-dist/ --sys-prefix && \
#    rm -rf /tmp/facets && \
#    fix-permissions "${CONDA_DIR}" && \
#    fix-permissions "/home/${NB_USER}"
```

With these changes, the docker container built does successfully run samgeo using pytorch.

**Comment by giswqs** [comment]
@JosephKuchar That's great to hear. Thank you for sharing the solution. You are welcome to contribute the dockerfile to samgeo.
